# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import quiz_pb2 as quiz__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in quiz_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuizServiceStub(object):
    """Serviço principal do Quiz
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartQuiz = channel.unary_unary(
                '/quiz.QuizService/StartQuiz',
                request_serializer=quiz__pb2.StartQuizRequest.SerializeToString,
                response_deserializer=quiz__pb2.StartQuizResponse.FromString,
                _registered_method=True)
        self.GetQuestion = channel.unary_unary(
                '/quiz.QuizService/GetQuestion',
                request_serializer=quiz__pb2.GetQuestionRequest.SerializeToString,
                response_deserializer=quiz__pb2.GetQuestionResponse.FromString,
                _registered_method=True)
        self.SubmitAnswer = channel.unary_unary(
                '/quiz.QuizService/SubmitAnswer',
                request_serializer=quiz__pb2.SubmitAnswerRequest.SerializeToString,
                response_deserializer=quiz__pb2.SubmitAnswerResponse.FromString,
                _registered_method=True)
        self.FinishQuiz = channel.unary_unary(
                '/quiz.QuizService/FinishQuiz',
                request_serializer=quiz__pb2.FinishQuizRequest.SerializeToString,
                response_deserializer=quiz__pb2.FinishQuizResponse.FromString,
                _registered_method=True)


class QuizServiceServicer(object):
    """Serviço principal do Quiz
    """

    def StartQuiz(self, request, context):
        """Inicia uma nova sessão de quiz
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuestion(self, request, context):
        """Obtém a próxima pergunta
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitAnswer(self, request, context):
        """Submete uma resposta
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishQuiz(self, request, context):
        """Finaliza o quiz e obtém resultado
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuizServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartQuiz': grpc.unary_unary_rpc_method_handler(
                    servicer.StartQuiz,
                    request_deserializer=quiz__pb2.StartQuizRequest.FromString,
                    response_serializer=quiz__pb2.StartQuizResponse.SerializeToString,
            ),
            'GetQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuestion,
                    request_deserializer=quiz__pb2.GetQuestionRequest.FromString,
                    response_serializer=quiz__pb2.GetQuestionResponse.SerializeToString,
            ),
            'SubmitAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAnswer,
                    request_deserializer=quiz__pb2.SubmitAnswerRequest.FromString,
                    response_serializer=quiz__pb2.SubmitAnswerResponse.SerializeToString,
            ),
            'FinishQuiz': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishQuiz,
                    request_deserializer=quiz__pb2.FinishQuizRequest.FromString,
                    response_serializer=quiz__pb2.FinishQuizResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quiz.QuizService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quiz.QuizService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuizService(object):
    """Serviço principal do Quiz
    """

    @staticmethod
    def StartQuiz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quiz.QuizService/StartQuiz',
            quiz__pb2.StartQuizRequest.SerializeToString,
            quiz__pb2.StartQuizResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quiz.QuizService/GetQuestion',
            quiz__pb2.GetQuestionRequest.SerializeToString,
            quiz__pb2.GetQuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quiz.QuizService/SubmitAnswer',
            quiz__pb2.SubmitAnswerRequest.SerializeToString,
            quiz__pb2.SubmitAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinishQuiz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quiz.QuizService/FinishQuiz',
            quiz__pb2.FinishQuizRequest.SerializeToString,
            quiz__pb2.FinishQuizResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
